### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by Abramovick** [bamlab/react-native-performance#1]
In `ReactNativeFlipper.java` file i think i need to import the library before doing `client.addPlugin(new RNPerfMonitorPlugin(reactInstanceManager))`. I'm not sure what the import package link is.... That's just my guess anyways, I'm not a java guy (I'm more javascript so maybe I'm wrong).

I get the error

```
/ReactNativeFlipper.java:48: error: cannot find symbol
      client.addPlugin(new RNPerfMonitorPlugin(reactInstanceManager));
                           ^
  symbol:   class RNPerfMonitorPlugin
  location: class ReactNativeFlipper
Note: /.../android/app/src/debug/java/com/safiri/ReactNativeFlipper.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
1 error

FAILURE: Build failed with an exception.
```

**Comment by Almouro** [comment]
Hi @Abramovick , import should be:

```java
import tech.bam.rnperformance.RNPerfMonitorPlugin;
```

I'll add this to the doc

(Usually I just open the android folder on Android Studio, then you get auto imports when you add code)

**Comment by Abramovick** [comment]
@Almouro thanks man
