### ISSUE TITLE
Expo support

### ISSUE THREAD

**Issue by fabio-alvarenga** [bamlab/react-native-performance#40]
Just chiming in to ask about the feasability of adding Expo support to the package.
I'm currently using Expo SDK 44, which supports native modules.

I'd be happy to help if you give me any pointers.
Thanks!

**Comment by Spoutnik97** [comment]
Hi! 
You can create an Expo plugin thanks to https://github.com/expo/config-plugins and Expo docs : https://docs.expo.dev/guides/config-plugins/

The main goal is to modify the native files (you get as a string) to the target files (as a string) with modifiers. These modifiers  are generally string modifier thanks to regex
It would be a pleasure to help you to create this plugin with you @fabio-alvarenga  ;)

**Comment by Almouro** [comment]
Hey @hirbod, yeah I confirm @Spoutnik97 didn't get a chance to implement it

By the way here are the new docs for the 0.68.0 installation on iOS https://github.com/bamlab/react-native-performance/pull/55/commits/1e7655ed59cc396967eb554fe58dd096dba981d9

**Comment by hirbod** [comment]
Thanks. That's easy. I'll finish the plug-in this week.
