### ISSUE TITLE
iOS build fails after updating rn-firebase packages

### ISSUE THREAD

**Issue by vladwhd** [bamlab/react-native-performance#5]
after a following update of packages 
![image](https://user-images.githubusercontent.com/58254981/116383296-0108cc00-a817-11eb-936d-9fee2e2e5e89.png)

I'm now getting this error when building the iOS app.
![image](https://user-images.githubusercontent.com/58254981/116383115-da4a9580-a816-11eb-9271-61b9ae1d4a30.png)

I also updated the target version in Podfile (to be able to `pod install` after the update), but I don't think it's related.
![image](https://user-images.githubusercontent.com/58254981/116383465-25fd3f00-a817-11eb-8030-e68e9a2b91a8.png)

**Comment by Almouro** [comment]
Hi @vladwhd and thanks for reporting! 🎈 

This should now be fixed in `0.4.0` 🎉

**Comment by vladwhd** [comment]
perfect, thank you @Almouro!
